### ISSUE TITLE
Can't compile on Ubuntu 25.10 with GCC 15.2

### ISSUE THREAD

**Issue by fkauffmann** [lronaldo/cpctelera#194]
Unrecoverable error when running setup.sh on Ubuntu 25.10.

My guess is that GCC 15 is much stricter about implicit declarations, now treated as errors by default.

Here is the content of my tools_building.log:

make: Entering directory '/home/fabrice/Retrocoding/cpctelera/cpctelera/tools'
[1;31;49m[ToolMaker][1;33;49m Building  2cdt...[0;39;49m
make[1]: Entering directory '/home/fabrice/Retrocoding/cpctelera/cpctelera/tools/2cdt'
Creating obj/ intermediate folder...
gcc -O3 -fsigned-char -DUNIX src/2cdt.c -c -o obj/2cdt.o
src/2cdt.c: In function ‘main’:
src/2cdt.c:1142:41: error: implicit declaration of function ‘toupper’ [-Wimplicit-function-declaration]
 1142 |                         TapeHeader[i] = toupper(pTapeFilename[i]);
      |                                         ^~~~~~~
src/2cdt.c:29:1: note: include ‘<ctype.h>’ or provide a declaration of ‘toupper’
   28 | #include "getopt.h"
  +++ |+#include <ctype.h>
   29 | 
src/2cdt.c:1268:29: error: implicit declaration of function ‘TZX_AppendFile’; did you mean ‘TZX_FreeFile’? [-Wimplicit-function-declaration]
 1268 |                             TZX_AppendFile(pTZXFile, pDestFilename);
      |                             ^~~~~~~~~~~~~~
      |                             TZX_FreeFile
make[1]: *** [Makefile:29: obj/2cdt.o] Error 1
make[1]: Leaving directory '/home/fabrice/Retrocoding/cpctelera/cpctelera/tools/2cdt'
make: *** [Makefile:74: 2cdt] Error 2
make: Leaving directory '/home/fabrice/Retrocoding/cpctelera/cpctelera/tools'
